# Generated by Django 4.2.30 on 2026-06-16 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('autor', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Цитата',
                'verbose_name_plural': 'Цитаты',
            },
        ),
        migrations.DeleteModel(
            name='Quotes',
        ),
    ]
